name: Run Tests

on:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - '**.yml'
  pull_request:
    branches:
      - main
    paths:
      - '**.py'
      - '**.yml'

jobs:
  test:
    name: Run test.py on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7.3, 3.10.1, 3.12.3]

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Install package
        run: pip install -e .

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)/src" >> $GITHUB_ENV

      - name: Run Tests
        run: python test.py
